---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build Docker image
        run: docker-compose build

      - name: Run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run lint
        run: docker-compose run --rm app sh -c "flake8"

---

